-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 20:48:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ConsuBanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ConsuBanco
-- -----------------------------------------------------

USE `ConsuBanco` ;

--
-- Table structure for table `Branch`
--

DROP TABLE IF EXISTS `Branch`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Branch` (
  `branchName` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `idBranch` bigint NOT NULL AUTO_INCREMENT,
  `client_id` bigint DEFAULT NULL,
  PRIMARY KEY (`idBranch`),
  KEY `FKhyfyhqtx6j9vhfliqi9l16e8m` (`client_id`),
  CONSTRAINT `FKhyfyhqtx6j9vhfliqi9l16e8m` FOREIGN KEY (`client_id`) REFERENCES `Client` (`idClient`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb3 COMMENT='	';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Client`
--

DROP TABLE IF EXISTS `Client`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Client` (
  `idClient` bigint NOT NULL AUTO_INCREMENT,
  `clientName` varchar(255) DEFAULT NULL,
  `phoneNum` varchar(255) DEFAULT NULL,
  `clientCol` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`idClient`)
) ENGINE=InnoDB AUTO_INCREMENT=134 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `client_has_branch`
--

DROP TABLE IF EXISTS `client_has_branch`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `client_has_branch` (
  `branch_id` bigint NOT NULL,
  `client_id` bigint NOT NULL,
  PRIMARY KEY (`branch_id`,`client_id`),
  KEY `FKbcvhglc9yo0dk3ctdttehkphi` (`client_id`),
  CONSTRAINT `FK7wgo76f59j88pa538mu85bdan` FOREIGN KEY (`branch_id`) REFERENCES `Branch` (`idBranch`),
  CONSTRAINT `FKbcvhglc9yo0dk3ctdttehkphi` FOREIGN KEY (`client_id`) REFERENCES `Client` (`idClient`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

-- -----------------------------------------------------
-- Table `ConsuBanco`.`Isr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`Isr` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`Isr` (
  `idIsr` VARCHAR(10) NOT NULL,
  `rate` DECIMAL(6,1) NULL,
  `factor` INT NULL,
  `annualBase` INT NULL,
  PRIMARY KEY (`idIsr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`InterestPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`InterestPlan` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`InterestPlan` (
  `idInterestPlan` VARCHAR(10) NOT NULL,
  `term` INT NULL,
  `amount` INT NULL,
  `interestRate` DECIMAL(15,3) NULL,
  PRIMARY KEY (`idInterestPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`InvestmentProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`InvestmentProduct` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`InvestmentProduct` (
  `idProduct` VARCHAR(10) NOT NULL,
  `productDescription` VARCHAR(45) NULL,
  `productCommercialName` VARCHAR(45) NULL,
  `term` VARCHAR(45) NULL,
  `investmentProfile` VARCHAR(45) NULL,
  `periodsInterest` INT NULL,
  `factor` INT NULL,
  `interestAnnualBase` INT NULL,
  `Isr_idIsr` VARCHAR(10) NOT NULL,
  `InterestPlan_idInterestPlan` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProduct`, `InterestPlan_idInterestPlan`),
  INDEX `fk_InvestmentProduct_Isr1_idx` (`Isr_idIsr` ASC) VISIBLE,
  INDEX `fk_InvestmentProduct_InterestPlan1_idx` (`InterestPlan_idInterestPlan` ASC) VISIBLE,
  CONSTRAINT `fk_InvestmentProduct_Isr1`
    FOREIGN KEY (`Isr_idIsr`)
    REFERENCES `ConsuBanco`.`Isr` (`idIsr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InvestmentProduct_InterestPlan1`
    FOREIGN KEY (`InterestPlan_idInterestPlan`)
    REFERENCES `ConsuBanco`.`InterestPlan` (`idInterestPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
